apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-k8s
  name: hello-k8s
spec:
  ports:
  - port: 8000
    nodePort: 32000
    name: server
  selector:
    app: hello-k8s
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
  labels:
    app: hello-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
      - name: hello-k8s-server
        image: python
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
            name: server
        command: ["/bin/bash", "-c"]
        args:
          - echo starting;
            git clone https://github.com/davidpeprah/hello-k8s.git;
            pip install -r /hello-k8s/requirements.txt;
            python3 /hello-k8s/app/main.py;
        readinessProbe:
          exec:
            command:
            - cat
            - /hello-k8s/app/main.py
          initialDelaySeconds: 30
          periodSeconds: 360
        livenessProbe:
          httpGet:
            path: /
            port: server
          initialDelaySeconds: 60
          periodSeconds: 30

